@Restaurants_API_HostAddress = https://localhost:7008
@token = CfDJ8JTmmV4OhTdGrfWl2kOFzwMg_n2ze-QCMTnW9qjwCdXm6lR-wOAjy-KUA4uz2gzYlY_Smw0puP64HZcyZ9DPxNQZXnCtfZxpZAis52zEO6kS2m12SOMFvbZtAUmNvJR_g6uD1lJADNhDKg5kcgZwZAsnLC9nnkUa9RhqvGTFwno-UbP4R_ehQd-cBKIaVuJISX0m215EwS6QnQ9X_WmCy2Lor60Rq9Hk1zOjmNhWZN7SnbdimSAZztaWgXdU72d7CRyvVLRUK5k0igYIRipAbS5_Ys63a7_I3-aX0IbRef1xTCCHjz9hLI3URhfT5AihxvcOT_ClBZ5ylLreriOufHtluXGrTac5k8POEzjeBUzhq2GsAtphcO9wYtE0c41_NlPexsyID4wbDLAWVHj43iGYIH2aNDxmedtUDuTftJleGPwSh421qJLjjb5Xq1YuGN6ng6jcfklsFZxbHl39h9C0xTMuMzR3bxsxejA2CsoI5qQ3IumKpCKtsqHP1c5qSlIThNvArSKwI8XVTe0Gfs2_mpdDCrK8dPOI6-vz56svrFh7SY4VJLtPxa79ql1PK5cBOwAwAroMl0M2sk0HqPmEKLPluqu3LJVbn_7aG2TIDwGzxOq4XFRmGVIrMgrPUM36wQ-Sogfkh_dCMLxDbK7csL55RrLibvMq0NttUELiuYu9u5y-HuRIohkjGihcIuHBfc2gFz89V2q9Hjzlnr6KueGZ64u-fIlyLAT0uD1GJGWhrqBxMPJ42U7J4UZRCpQnL5Gyo3kdTHYfAk9iz-TZI2zMCm3hjmA4H7GCrgyp


GET {{Restaurants_API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}

###

GET {{Restaurants_API_HostAddress}}/api/restaurants/3
Authorization : Bearer {{token}}

###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}    
Content-Type: application/json

{
    "Name": "Burger Bun Gestone Park",
    "Description" : "Burger restaurant Gestone Park",
    "Category" : "Sri Lankan",
    "ContactEmail" : "sds@gmail.com",
    "ContactNumber" : "2343",
    "PostCode" : "33-535"

}

###

DELETE {{Restaurants_API_HostAddress}}/api/restaurants/7

###

PATCH {{Restaurants_API_HostAddress}}/api/restaurants/6
Content-Type: application/json

{
    "id": 6,
    "name": "Cham's Rest 1234",
    "description": "New SL restaurant 3",
    "category": "Sri Lankan",
    "hasDelivery": false,
    "city": "Noble park",
    "street": "500 hshshs VCC",
    "postCode": null 
}

###

POST {{Restaurants_API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
  "Name" : "Double Cheese Burger",
  "Description" : "Home made burger",
  "Price" : 18,
  "KiloCalories" : 220
}

###

GET {{Restaurants_API_HostAddress}}/api/restaurant/3/dishes

###

GET {{Restaurants_API_HostAddress}}/api/restaurant/3/dishes/5

###

DELETE {{Restaurants_API_HostAddress}}/api/restaurant/37/dishes

###
POST {{Restaurants_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email" : "owner@test.com",
    "password" : "Password1$"
}

###
POST {{Restaurants_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email" : "owner@test.com",
    "password" : "Password1$"
}