@Restaurants_API_HostAddress = https://localhost:7008
@token = CfDJ8JTmmV4OhTdGrfWl2kOFzwO9BMehBm2CfWqWSuOnfB-E1hffX-kITmrUP8ZVcn5qd9tKv4pdSYumXLk6_nybbKPun68eVGqNz98jB4XrFtu47ibkJ-P0FU8A8mQeJ-YV6VIUlA7RlzCNh17G1fi4wEaot90DAOeWMA-QcWt_2LemyWI2t_qn4fNciq2F-TsHCoMNaxijF7gxqmyIx5x6NWjjOd1kTJDyva91T2FK0jl3DLTHYNXDU1B9OTRjqniV96dzmSY4tinSS95lcZlkv37zX0v0lTNRYpfuSdmwruzJoo6cqykqGQA0V1EAiYiLAdo8LZxJ2-UKjQSeccW5NdquLGl64wEq9y2mFVAM7neEQgGtoDQ0hdpmD7yKAsvSgXzm2s9tY2JzL6X6qNQfZr2LCStgbQ2MWXkcZ0lE0DgGvR6NqGAGpl8XRmEOxQ3JbQlxiqjCDVczsGFXPfX4KkwC9g9gWpnz-HTtRs3kJNvZW4TXgm-4a8SwV1Em7AT5KsckhMwjGiIX5Bs9k9f7gB4tafMe-YkQSoxCeZBLzpUK3fFLdPZLqSu8xu7IcbMvB8XCPAv1ZMy73zEYQMPo10vfaTB-nb9Cp2wqm6hPYZLxTho8B1syT9HBCsOa1yqwo3f9eRNukJmJ-FnSG1iXCKK2ZMoy7He96iKXXtL6nTDb5rQ0x4LxU9YXccs-Nk3S2n4AIPAL9q2b0pjKfuOeYKLSMoixp4Lkw7rlLZqEhFnI___JBzMbWBbL9nTchHnO3_dki8zMMQT8fpvG2fZhJ0Bq4T_GSZChsg3uZMmzEEvz



GET {{Restaurants_API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}

###

GET {{Restaurants_API_HostAddress}}/api/restaurants/5
Authorization : Bearer {{token}}

###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}    
Content-Type: application/json

{
    "Name": "Owner Restaurant",
    "Description" : "Owners Restaurant Beef and Chicken",
    "Category" : "Sri Lankan",
    "ContactEmail" : "oz@gmail.com",
    "ContactNumber" : "0022656",
    "PostCode" : "43-678"

}

###

DELETE {{Restaurants_API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}

###

PATCH {{Restaurants_API_HostAddress}}/api/restaurants/5
Content-Type: application/json
Authorization : Bearer {{token}}

{    
    "name": "Updated name",
    "Description" : "Updated description",
    "HasDelivery" : false,
     "Category" : "Sri Lankan"
   
}

###

POST {{Restaurants_API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
  "Name" : "Double Cheese Burger",
  "Description" : "Home made burger",
  "Price" : 18,
  "KiloCalories" : 220
}

###

GET {{Restaurants_API_HostAddress}}/api/restaurant/3/dishes
Authorization : Bearer {{token}}

###

GET {{Restaurants_API_HostAddress}}/api/restaurant/3/dishes/5

###

DELETE {{Restaurants_API_HostAddress}}/api/restaurant/37/dishes

###
POST {{Restaurants_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email" : "owner@test.com",
    "password" : "Password1$"
}

###
POST {{Restaurants_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email" : "user@test.com",
    "password" : "Password1$"
}

###

PATCH {{Restaurants_API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality" : "French",
  "DateOfBirth" : "2015-07-10"
}

###
