@Restaurants_API_HostAddress = https://localhost:7008
@token = CfDJ8JTmmV4OhTdGrfWl2kOFzwOIu8tW2qel4pfJBCLFMWcBryxM_9sBXdiH4mabvjz5XqSFITCJjjlGPPHcZuAbYv9cI4QJNt4LytLhJ60bTQPIAGyPjbuIlY3Xbm02pKo22aJxdr-FNzCXEmBPpmhtpx0IuasDr2gBrsdLoepjzJgdpJ8HH1xo83I08VKLfcIiax-no0GX9UZtv8qesgp1W__nlW9hwUIZqNCSMB9ofJ1whb6cIj38N7dKTuSHCd2zcaVY8BhAcHZ8mJZRy662IcdS90hdlHCv7GeA5H1OscWFx1e21WeMB_JDd2NSa99MWiQ6ihMOPfiuGAV4zuke0DhGhoryO3BWtvHziQT7i5KhljatH8mwtuoUMvE8iyUk0eejz6ZyN1wuxXMs3BCfaHqHIlKRfX1QbkDCYmsErjBUpE3bzw3RL0UsD00k8c1ucSlK-RYpE1uZapVi0TwquhTB8H_AHXRuo7cMh_XERw2_WVWYxWJxAMmqujDMtCl8W7uxdgAF_9OWhn7Xt84X5MbAuPFU0ivTYa9mwRmPw3y8tpOMqvixeeqDXDInWWLO7qtXevg53oHhTuERTIFtATmbfHIZF4sk1DpaqBkhSpFdvwpjAa1E1s3NXPPHqBvQJ5rzF0QBK6AU5zfwxOcAq2T4WxJo4oxjJRpJQWfQzkk219Ur2CaXYXdp_VgqUTH0Bf5dth07TCzNuk1W2ef0eiPBstlgtpuX6XOS_1O1PdYOw1AKTgZeZmVIWytAtYGSbsuZt4mBBVpYDVBygY-yoAjcVekjh8A1xV29YTIgHbsj



GET {{Restaurants_API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=5&pageNumber=1
Authorization : Bearer {{token}}

###

GET {{Restaurants_API_HostAddress}}/api/restaurants/5
Authorization : Bearer {{token}}

###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Authorization : Bearer {{token}}    
Content-Type: application/json

{
    "Name": "Owner2 Restaurant2",
    "Description" : "Owners Restaurant Beef and Chicken",
    "Category" : "Sri Lankan",
    "ContactEmail" : "oz@gmail.com",
    "ContactNumber" : "0022656",
    "PostCode" : "43-678"

}

###

DELETE {{Restaurants_API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}

###

PATCH {{Restaurants_API_HostAddress}}/api/restaurants/5
Content-Type: application/json
Authorization : Bearer {{token}}

{    
    "name": "Updated name",
    "Description" : "Updated description",
    "HasDelivery" : false,
     "Category" : "Sri Lankan"
   
}

###

POST {{Restaurants_API_HostAddress}}/api/restaurant/3/dishes
Content-Type: application/json

{
  "Name" : "Double Cheese Burger",
  "Description" : "Home made burger",
  "Price" : 18,
  "KiloCalories" : 220
}

###

GET {{Restaurants_API_HostAddress}}/api/restaurant/3/dishes
Authorization : Bearer {{token}}

###

GET {{Restaurants_API_HostAddress}}/api/restaurant/3/dishes/5

###

DELETE {{Restaurants_API_HostAddress}}/api/restaurant/37/dishes

###
POST {{Restaurants_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email" : "owner2@test.com",
    "password" : "Password1$"
}

###
POST {{Restaurants_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email" : "owner2@test.com",
    "password" : "Password1$"
}

###

PATCH {{Restaurants_API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality" : "French",
  "DateOfBirth" : "2015-07-10"
}

###

POST {{Restaurants_API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail" : "owner2@test.com",
  "RoleName" : "Owner"
}

###
